project_id = "makerspace"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.email]
enable_signup = true
enable_confirmations = true
otp_length = 6
otp_expiry = 600
max_frequency = "1m0s"

[auth.email.smtp]
host = "smtp.resend.com"
port = 465
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "makerspace@moonlight.ng"
sender_name = "Makerspace"

[auth.email.template.magic_link]
subject = "Your Makerspace Studio code"
content_path = "./supabase/templates/studio-login.html"

[auth.email.template.confirmation]
subject = "Your Makerspace Studio code"
content_path = "./supabase/templates/studio-login.html"

[auth.rate_limit]
email_sent = 60

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
